### PR TITLE
Make background color of GTK+2 progress bars consistent with GTK+3

### PR DESCRIPTION
**Pull request by livanh**
I noticed a difference between GTK+2 and GTK+3 in the derivation of the background color of progress bars. This is not apparent in light themes but quite visible in dark themes. So I changed GTK+2 to use the same method as GTK+3.

### CODE REVIEW

**Comment by livanh** [comment]
I am still a little unsure, maybe a few screenshots can help us.

This is how GTK+3 looks on master with a dark theme:
gtk3-original

And this is GTK+2:
gtk2-original
I remember that it used to look similar to GTK+3, and I preferred it that way (or it's just my resistance to change).

The odd thing is that if I edit GTK+3 with "background-color: mix($bg_color, $base_color, 0.08);", it still looks very similar (and different from GTK+2). Instead, with "background-color: mix($base_color, $bg_color, 0.08);" it looks similar to GTK+2:
gtk3-changed

What is the intended look w.r.t. these screenshots?

**Comment by actionless** [comment]
2nd and 3rd screenshots are looking fine

so yeah, current gtk+3 need to be fixed

**Comment by actionless** [comment]
regarding your last point: i think the order of arguments is different in `mix` functions

**Comment by actionless** [comment]
thanks, now i see travis complains on scss codestyle: https://travis-ci.com/themix-project/oomox-gtk-theme/builds/110622532

and also i guess the screenshots would need to be updated to represent the change, https://github.com/themix-project/oomox-gtk-theme#generate-new-screenshots
```
# start container mounting the current dir:
./docker_scripts/dev_docker_container.sh
# Generate new screenshots:
./docker_scripts/run_docker_tests.sh -e GENERATE_ASSETS=1
```

**Comment by actionless** [comment]
rich diff on github rules :3 

now we can definitely see what your fix was effective :)

2019-05-08--1557347544_1599x1081_scrot


thanks a lot for all your effort!

**Comment by livanh** [comment]
You're welcome! I didn't know about the rich diff, it's nice indeed!

**Pull request merged**
